@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FinanceTrackerParser" as FinanceTrackerParser LOGIC_COLOR
participant ":ConvertBookmarkExpenseCommand" as ConvertBookmarkExpenseCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
end box

box BookmarkExpense UI_COLOR_T1
participant ":BookmarkExpense" as BookmarkExpense UI_COLOR
end box

[->LogicManager: execute("convert-bookmark-expense 1 d/20/10/2020")
activate LogicManager LOGIC_COLOR

LogicManager -> FinanceTrackerParser: parseCommand("convert-bookmark-expense 1 d/20/10/2020")
activate FinanceTrackerParser LOGIC_COLOR

create ConvertBookmarkExpenseCommand LOGIC_COLOR
FinanceTrackerParser -> ConvertBookmarkExpenseCommand: ConvertBookmarkExpenseCommand()
activate ConvertBookmarkExpenseCommand LOGIC_COLOR

ConvertBookmarkExpenseCommand --> FinanceTrackerParser
deactivate ConvertBookmarkExpenseCommand

FinanceTrackerParser --> LogicManager
deactivate FinanceTrackerParser

LogicManager -> ConvertBookmarkExpenseCommand: execute()
activate ConvertBookmarkExpenseCommand LOGIC_COLOR

ConvertBookmarkExpenseCommand -> ModelManager: getFilteredBookmarkExpenseList()
activate ModelManager MODEL_COLOR

ModelManager --> ConvertBookmarkExpenseCommand: bookmarkExpenseList
deactivate ModelManager

ConvertBookmarkExpenseCommand -> BookmarkExpense: bookmarkExpenseList.get(Index)
activate BookmarkExpense UI_COLOR

BookmarkExpense --> ConvertBookmarkExpenseCommand: BookmarkExpense

ConvertBookmarkExpenseCommand -> BookmarkExpense: convert(Date)

BookmarkExpense --> ConvertBookmarkExpenseCommand: Expense

deactivate BookmarkExpense
'Hidden arrow to position the destroy marker below the end of the activation bar.
BookmarkExpense -[hidden]-> ConvertBookmarkExpenseCommand
destroy BookmarkExpense

ConvertBookmarkExpenseCommand -> ModelManager: addExpense()
activate ModelManager MODEL_COLOR

ModelManager --> ConvertBookmarkExpenseCommand
deactivate ModelManager

ConvertBookmarkExpenseCommand --> LogicManager: result
deactivate ConvertBookmarkExpenseCommand

[<-- LogicManager: result
deactivate LogicManager
@enduml
