@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FinanceTrackerParser" as FinanceTrackerParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant ":DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "cmd:DeleteExpenseCommand" as DeleteExpenseCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> FinanceTrackerParser : parseCommand("delete 1")
activate FinanceTrackerParser

create DeleteCommandParser
FinanceTrackerParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> FinanceTrackerParser
deactivate DeleteCommandParser

FinanceTrackerParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser
deactivate DeleteCommand

DeleteCommandParser --> FinanceTrackerParser
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> FinanceTrackerParser
destroy DeleteCommandParser

create DeleteExpenseCommand
FinanceTrackerParser -> DeleteExpenseCommand
activate DeleteExpenseCommand

DeleteExpenseCommand -> DeleteCommand : getTargetIndex()
activate DeleteCommand

DeleteCommand --> DeleteExpenseCommand
deactivate DeleteCommand

DeleteCommand -[hidden]-> FinanceTrackerParser
destroy DeleteCommand

DeleteExpenseCommand --> FinanceTrackerParser : cmd
deactivate DeleteExpenseCommand

FinanceTrackerParser --> LogicManager : cmd
deactivate FinanceTrackerParser

LogicManager -> DeleteExpenseCommand : execute()
activate DeleteExpenseCommand

DeleteExpenseCommand -> ModelManager : getFilteredExpenseList()
activate ModelManager

ModelManager --> DeleteExpenseCommand
deactivate ModelManager

create CommandResult
DeleteExpenseCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteExpenseCommand
deactivate CommandResult

DeleteExpenseCommand --> LogicManager : result
deactivate DeleteExpenseCommand

[<--LogicManager
deactivate LogicManager
@enduml
