@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyFinanceTracker <<Interface>>
Interface Model <<Interface>>
Class FinanceTracker
Class ReadOnlyFinanceTracker
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Transaction {
Class "{abstract}\nTransaction" as Transaction
Class Expense
Class Income
Class Amount
Class CalculatedAmount
Class Date
Class Title
Class TransactionList
}

Package Category {
Class Category
}

Package Budget {
Class MonthlyBudget
}

Package Bookmark {
Class BookmarkExpense
Class BookmarkExpenseList
Class BookmarkIncome
Class BookmarkIncomeList
Class "{abstract}\nBookmarkTransaction" as BookmarkTransaction
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

FinanceTracker .up.|> ReadOnlyFinanceTracker

ModelManager .up.|> Model
ModelManager o--> "1" FinanceTracker
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

FinanceTracker *--> "1" TransactionList
TransactionList o-left-> "*" Transaction
Expense -up-|> Transaction
Income -up-|> Transaction
Transaction *-up-> "1" Title
Transaction *-up-> "1" Amount
Transaction *--> "1" Date
Transaction *--> "*" Category

FinanceTracker *--> "1" BookmarkExpenseList
FinanceTracker *--> "1" BookmarkIncomeList
BookmarkExpenseList o--> "*" BookmarkTransaction
BookmarkIncomeList o--> "*" BookmarkTransaction
BookmarkExpense -up-|> BookmarkTransaction
BookmarkIncome -left-|> BookmarkTransaction
BookmarkTransaction --> Transaction
BookmarkTransaction *--> "1" Title
BookmarkTransaction *--> "1" Amount
BookmarkTransaction *--> "*" Category

FinanceTracker *--> "1" MonthlyBudget
CalculatedAmount ..> Amount
MonthlyBudget --> CalculatedAmount
MonthlyBudget --> Amount

ModelManager -->"*" Transaction : filtered list
@enduml
