@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyFinanceTracker <<Interface>>
Interface Model <<Interface>>
Class FinanceTracker
Class ReadOnlyFinanceTracker
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Transaction {
Class "{abstract}\nTransaction" as Transaction
Class Expense
Class Income
Class Amount
Class Date
Class Title
Class TransactionList
}

Package Category {
Class Category
}

Package Budget {
Class MonthlyBudget
Class MonthlyExpenseLimit
}

Package Savings {
Class MonthlySavings
Class MonthlySavingsGoal
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

FinanceTracker .up.|> ReadOnlyFinanceTracker

ModelManager .up.|> Model
ModelManager o--> "1" FinanceTracker
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

FinanceTracker *--> "1" TransactionList
TransactionList o--> "*" Transaction
Expense -left-|> Transaction
Income -right-|> Transaction
Transaction *--> "1" Title
Transaction *--> "1" Amount
Transaction *--> "1" Date
Transaction *--> "*" Category

FinanceTracker *--> "1" MonthlySavings
MonthlySavings *--> "1" MonthlySavingsGoal
FinanceTracker *--> "1" MonthlyBudget
MonthlyBudget *--> "1" MonthlyExpenseLimit

Title -[hidden]right-> Amount
Amount -[hidden]right-> Date

ModelManager -->"*" Transaction : filtered list
@enduml
