@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyFinanceTracker <<Interface>>
Interface Model <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Class FinanceTracker
Class Model
Class ModelManager
Class UserPrefs

Package Transaction {
Class "{abstract}\nTransaction" as Transaction
Class Expense
Class Income
Class Amount
Class Date
Class Title
Class TransactionList
}

Package Category {
Class Category
}

Package Budget {
Class MonthlyBudget
}

Package Bookmark {
Class BookmarkExpenseList
Class BookmarkIncomeList
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

FinanceTracker .up.|> ReadOnlyFinanceTracker

ModelManager .up.|> Model
ModelManager o--> "1" FinanceTracker
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

FinanceTracker *--> "1" TransactionList
TransactionList o--> "*" Transaction
Expense -left-|> Transaction
Income -right-|> Transaction
Transaction *--> "1" Title
Transaction *--> "1" Amount
Transaction *--> "1" Date
Transaction *--> "*" Category

FinanceTracker *--> "1" BookmarkExpenseList
FinanceTracker *--> "1" BookmarkIncomeList

FinanceTracker *--> "1" MonthlyBudget

TransactionList -[hidden]right-> BookmarkExpenseList
BookmarkIncomeList -[hidden]down-> BookmarkExpenseList
BookmarkExpenseList -[hidden]down-> MonthlyBudget
ModelManager -[hidden]right-> FinanceTracker

ModelManager --> "*" Transaction : filtered list
ModelManager o--> "1" MonthlyBudget

@enduml
