@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class ResultDisplay
Class TransactionListPanel
Class TransactionCard
Class CommandBox
Class SavingsGoalPanel
Class UiState
Class DisabledWindow

package Tabs {
Class TwoColumnTabPane
Class OverviewTabPane
Class IncomeTabPane
Class ExpenseTabPane
Class AnalyticsTabPane
Class UserGuideTabPane
}

package Expense {
Class ExpensePanel
}

package Income {
Class IncomePanel
}

package Bookmark {
Class BookmarkIncomePanel
Class BookmarkExpensePanel
Class BookmarkTransactionCard
}
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
UiManager --> UiState
MainWindow --> UiState
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-up-> DisabledWindow

MainWindow *-down-> OverviewTabPane
MainWindow *-down-> IncomeTabPane
MainWindow *-down-> ExpenseTabPane
MainWindow *-down-> AnalyticsTabPane
MainWindow *-down-> UserGuideTabPane

OverviewTabPane *-down-> TransactionListPanel
OverviewTabPane *-down-> SavingsGoalPanel

IncomeTabPane *-down-> IncomePanel
IncomeTabPane *-down-> BookmarkIncomePanel

ExpenseTabPane *-down-> ExpensePanel
ExpenseTabPane *-down-> BookmarkExpensePanel

TransactionListPanel -down-> TransactionCard
ExpensePanel -down-> TransactionCard
IncomePanel -down-> TransactionCard

BookmarkExpensePanel -down-> BookmarkTransactionCard
BookmarkIncomePanel -down-> BookmarkTransactionCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
TransactionListPanel --|> UiPart
TransactionCard --|> UiPart
ExpensePanel --|> UiPart
IncomePanel --|> UiPart
SavingsGoalPanel --|> UiPart
BookmarkExpensePanel --|> UiPart
BookmarkIncomePanel --|> UiPart
BookmarkTransactionCard --|> UiPart

TwoColumnTabPane --|> UiPart
OverviewTabPane --|> TwoColumnTabPane
IncomeTabPane --|> TwoColumnTabPane
ExpenseTabPane --|> TwoColumnTabPane

AnalyticsTabPane --|> UiPart
UserGuideTabPane --|> UiPart

TransactionCard ..> Model
UiManager -up-> Logic
MainWindow -up-> Logic

CommandBox -[hidden]left- ResultDisplay
ExpensePanel -[hidden]left- TransactionListPanel
IncomePanel -[hidden]left- SavingsGoalPanel

MainWindow -[hidden]-|> UiPart
AnalyticsTabPane -[hidden]-|> OverviewTabPane
UserGuideTabPane -[hidden]-|> OverviewTabPane
TwoColumnTabPane -[hidden]down-|> SavingsGoalPanel
UiPart -[hidden]down-|> Model
Logic -[hidden]down-|> UiManager
TwoColumnTabPane -[hidden]down-|> TransactionListPanel
@enduml
