@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FinanceTrackerParser" as FinanceTrackerParser LOGIC_COLOR
participant ":ConvertFrequentExpenseCommand" as ConvertFrequentExpenseCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
end box

box FrequentExpense UI_COLOR_T1
participant ":FrequentExpense" as FrequentExpense UI_COLOR
end box

[->LogicManager: execute("convert-frequent-expense 1 d/20/10/2020")
activate LogicManager LOGIC_COLOR

LogicManager -> FinanceTrackerParser: parseCommand("convert-frequent-expense 1 d/20/10/2020")
activate FinanceTrackerParser LOGIC_COLOR

create ConvertFrequentExpenseCommand LOGIC_COLOR
FinanceTrackerParser -> ConvertFrequentExpenseCommand: ConvertFrequentExpenseCommand()
activate ConvertFrequentExpenseCommand LOGIC_COLOR

ConvertFrequentExpenseCommand --> FinanceTrackerParser
deactivate ConvertFrequentExpenseCommand

FinanceTrackerParser --> LogicManager
deactivate FinanceTrackerParser

LogicManager -> ConvertFrequentExpenseCommand: execute()
activate ConvertFrequentExpenseCommand LOGIC_COLOR

ConvertFrequentExpenseCommand -> ModelManager: getFilteredFrequentExpenseList()
activate ModelManager MODEL_COLOR

ModelManager --> ConvertFrequentExpenseCommand: frequentExpenseList
deactivate ModelManager

ConvertFrequentExpenseCommand -> FrequentExpense: frequentExpenseList.get(Index)
activate FrequentExpense UI_COLOR

FrequentExpense --> ConvertFrequentExpenseCommand: FrequentExpense

ConvertFrequentExpenseCommand -> FrequentExpense: convert(Date)

FrequentExpense --> ConvertFrequentExpenseCommand: Expense

deactivate FrequentExpense
'Hidden arrow to position the destroy marker below the end of the activation bar.
FrequentExpense -[hidden]-> ConvertFrequentExpenseCommand
destroy FrequentExpense

ConvertFrequentExpenseCommand -> ModelManager: addExpense()
activate ModelManager MODEL_COLOR

ModelManager --> ConvertFrequentExpenseCommand
deactivate ModelManager

ConvertFrequentExpenseCommand --> LogicManager: result
deactivate ConvertFrequentExpenseCommand

[<-- LogicManager: result
deactivate LogicManager
@enduml
