# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'jekyll'
gem 'minima'
gem 'jekyll-coffeescript'
gem 'jekyll-default-layout'
gem 'jekyll-gist'
gem 'jekyll-github-metadata'
gem 'jekyll-optional-front-matter'
gem 'jekyll-paginate'
gem 'jekyll-readme-index'
gem 'jekyll-titles-from-headings'
gem 'jekyll-relative-links'
gem 'wdm', '~> 0.1.0' if Gem.win_platform?
gem 'jekyll-spaceship', git: 'https://github.com/AY2021S1-CS2103T-W16-3/jekyll-spaceship.git'
